name: ACCELQ Github Action CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Save Temporary Login URL To File
      id: sfdx_temp_auth_url
      if: always()
      run: |
          echo "{\"status\":0,\"result\":{\"orgId\":\"00D530000006G86EAE\",\"url\":\"https://platform-site-4982-dev-ed.scratch.my.salesforce.com/secur/frontdoor.jsp?sid=00D530000006G86!AQwAQDO3uIU0UFv9.e_RGQD8bhk9b6o4amThKeTNUlLHvnIw5pHwQpEH5qr3ajOIXbCjPfbrb0Wwx.eU4440PXa8QcxeT2ro\",\"username\":\"test-wuoercs85plc@example.com\"}}"
    - name: Test
      run: echo "${{ toJSON(steps.sfdx_temp_auth_url) }}"
#     - name: ACCELQ Github-A Connect
#       # You may pin to the exact commit or the version.
#       # uses: accelq/accelq-ci-github-actions@953369c4991322d0eb25d68f449a7d8c574c58d1
#       uses: accelq/accelq-ci-github-actions@v1.1
#       env:
#         TEST_VARIABLE: "apple"
#       with:
#         # Your ACCELQ Application URL in the exact following format: https://<hostname>:<port_num>
#         appURL: "https://poc.accelq.io"
#         # Your ACCELQ User ID
#         userName: "vivek.burman@accelq.com"
#         # API key available in Profile section of ACCELQ
#         apiKey: "MkcmCQ-_4f61gt-0BWOA6FIavGYTovljJi_9JzzDLAE"
#         # Tenant Code displayed in the Profile section of ACCELQ
#         tenantCode: "demo"
#         # This ID should come from the CI job you saved in ACCELQ application
#         jobId: "383564"
#         # Run Params(optional) should be JSON string form example: '{"username": "John Todd", "password": "bxW&=UVw"}'
#         runParam: ${{ format('{{"username":{0},"isScratchOrg":"true"}}', steps.TEST_VARIABLE) }}
